

module.exports = {
  items: [
    {
      title: "Kitchen aid single wall oven",
      desc: "30 inch Kitchen aid single wall oven .(convection oven )  Never been used . Displayed in our model home . ",
      price: "$700",
      post: "2016-09-21  9:05pm",
      location: "$700",
      category: "appliances - by owner"},
    {
      title: "Vintage Stan Petersen F1 Car Painting",
      desc: "Vintage Stan Petersen  Car Painting From 1967 -  31 1/2 \" x 25 1/2 \"",
      price: "$500",
      post: "2016-09-05  1:55pm",
      location: "$500",
      category: "antiques - by owner"},
    {
      title: "Sewing Machine",
      desc: "Antique Westinghouse Wheeler Rotary in cabinet. Needs tuning up but it works. It has a knee pedal.    ",
      price: "$40",
      post: "2016-09-17 10:37pm",
      location: "$40",
      category: "antiques - by owner"},
    {
      title: "JAPANEESE PICTURES",
      desc: "Set of 2 Japanese Pictures In Black & Gold Frames.    ",
      price: "$20",
      post: "2016-09-21  9:22pm",
      location: "$20",
      category: "antiques - by owner"},
    {
      title: "Halloween Costumes-Incredible Hulk, Wolverine and Doctor",
      desc: "Incredible Hulk Costume-Fits Toddler Size 2-4   $10",
      price: "$10",
      post: "2016-08-23  3:57pm",
      location: "$10",
      category: "baby & kid stuff - by owner"},
    {
      title: "Healthy Care Booster Seat By Fisher-Price",
      desc: "The Fisher-Price Heathy Care Booster seat is a portable, folding booster seat that keeps baby's feeding surface clean and sanitized, while offering all the features that parents and toddlers need. The removable feeding tray can be dishwashed to sanitize, plus the snap-on cover allows parents to keep it clean in transport. The tray has three tummy adjustments and three height adjustments to allow for growing children and it lets the caregiver remove the mess. Plus, the seat back is removable for older toddlers. Includes an easy fold for compact storage, restraint straps that connect to the chair and secure baby, and shoulder straps for carrying when on-the-go. Minimal assembly required. Measures approximately 9\" H x 15 1/2\" W x 13\" D.",
      price: "$20",
      post: "2016-09-03  4:55pm",
      location: "$20",
      category: "baby & kid stuff - by owner"},
    {
      title: "BRAND NEW never opened URBINI infant car seat",
      desc: "This Is a very popular car seat and is currently sold out at Walmart, the normal price is $100 and the I am selling it for only $80.00. I got two car seats from my baby shower and I only need one. Please let me know if you are interested.",
      price: "$80",
      post: "2016-09-21  8:57pm",
      location: "$80",
      category: "baby & kid stuff - by owner"},
    {
      title: "Original xbox/controller/games",
      desc: "Asking $140 or a cool trade.    ",
      price: "NULL",
      post: "2016-09-21  8:55pm",
      location: "NULL",
      category: "barter"},
    {
      title: "Gitzo Tripod",
      desc: "Gitzo G1257 Mountaineer Reporter Carbon 6X",
      price: "NULL",
      post: "2016-09-21  9:01pm",
      location: "NULL",
      category: "barter"},
    {
      title: "ON A BUDGET? CALL US ON YOUR NEW FLOOR OR CARPET INSTALLING 639-9809 (",
      desc: "NEED NEW CARPET, HARDWOOD FLOOR OR TILE INSTALLING? ",
      price: "NULL",
      post: "2016-08-31  9:25am",
      location: "NULL",
      category: "business/commercial - by dealer"},
    {
      title: "Sisneros Professional Custom Designed Office Furniture Suite",
      desc: "Gorgeous Hand Crafted Office Furniture by Sisneros Custom Design, included are the following pieces, all are in gorgeous condition with no damage. These came from a home office in Blackhawk.",
      price: "$799",
      post: "2016-09-21  8:48pm",
      location: "$799",
      category: "business/commercial - by dealer"},
    {
      title: "Indoor Cycling Bicycle Stationary Training Rollers 251265",
      desc: "Indoor Cycling Bicycle Stationary Training Rollers 251265",
      price: "$145",
      post: "2016-09-21  8:52pm",
      location: "$145",
      category: "business/commercial - by dealer"},
    {
      title: "Screen printing equipments",
      desc: "Screen printer 4 color",
      price: "$1099",
      post: "2016-09-21  9:03pm",
      location: "$1099",
      category: "business/commercial - by owner"},
    {
      title: "Restaurant Stainless Steel Hand Sink",
      desc: "Wall Mount Stainless Steel Hand Sink - Brand New ",
      price: "$79",
      post: "2016-09-21  9:22pm",
      location: "$79",
      category: "business/commercial - by owner"},
    {
      title: "Titus el guapo 26er",
      desc: "Custom made 2013 V3 Titus el guapo meduim",
      price: "$1499",
      post: "2016-08-27  7:04pm",
      location: "$1499",
      category: "bicycles - by owner"},
    {
      title: "Specialized Hotrock 20\" Boys Coaster bike",
      desc: "Our son has outgrown his 5-yr old bike.  He didn't ride it all that much so it still works great as a coaster bike (using the pedal brakes), but the hand brake needs some work to fix.  The edge of the handlebar grip is also showing some wear. The picture is the hero shot of the 2012 model which looks pretty much the same as ours.",
      price: "$50",
      post: "2016-09-21  9:02pm",
      location: "$50",
      category: "bicycles - by owner"},
    {
      title: "2015 Felt Z3 Ultegra",
      desc: "2015 Felt Z3 in great condition ",
      price: "NULL",
      post: "2016-09-21  9:04pm",
      location: "NULL",
      category: "bicycles - by owner"},
    {
      title: "1948 Monterey Clipper",
      desc: "1948 Monterey Clipper sport fisher -- 28 feet",
      price: "$5000",
      post: "2016-09-21  8:58pm",
      location: "$5000",
      category: "boats - by owner"}
  ]
};
